# automatically generated by the FlatBuffers compiler, do not modify

# namespace: wire

class AggFn(object):
    Count = 0
    Sum = 1
    Mean = 2
    Min = 3
    Max = 4
    Collect = 5
    First = 6
    Last = 7
