# automatically generated by the FlatBuffers compiler, do not modify

# namespace: wire

class Command(object):
    NONE = 0
    InsertCmd = 1
    FindCmd = 2
    CountCmd = 3
    ExistsCmd = 4
    UpdateCmd = 5
    ReplaceCmd = 6
    DeleteCmd = 7
    VectorSearchCmd = 8
    TextSearchCmd = 9
    HybridSearchCmd = 10
    GroupCmd = 11
    StatsCmd = 12
    IndexCmd = 13
