# automatically generated by the FlatBuffers compiler, do not modify

# namespace: wire

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class CountCmd(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = CountCmd()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsCountCmd(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    @classmethod
    def CountCmdBufferHasIdentifier(cls, buf, offset, size_prefixed=False):
        return flatbuffers.util.BufferHasIdentifier(buf, offset, b"\x4D\x4F\x4F\x52", size_prefixed=size_prefixed)

    # CountCmd
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # CountCmd
    def Filter(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            from mooracer.wire.Value import Value
            obj = Value()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

def CountCmdStart(builder):
    builder.StartObject(1)

def Start(builder):
    CountCmdStart(builder)

def CountCmdAddFilter(builder, filter):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(filter), 0)

def AddFilter(builder, filter):
    CountCmdAddFilter(builder, filter)

def CountCmdEnd(builder):
    return builder.EndObject()

def End(builder):
    return CountCmdEnd(builder)
