# automatically generated by the FlatBuffers compiler, do not modify

# namespace: wire

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class DeleteCmd(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = DeleteCmd()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsDeleteCmd(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    @classmethod
    def DeleteCmdBufferHasIdentifier(cls, buf, offset, size_prefixed=False):
        return flatbuffers.util.BufferHasIdentifier(buf, offset, b"\x4D\x4F\x4F\x52", size_prefixed=size_prefixed)

    # DeleteCmd
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # DeleteCmd
    def Filter(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            from mooracer.wire.Value import Value
            obj = Value()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # DeleteCmd
    def Many(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

def DeleteCmdStart(builder):
    builder.StartObject(2)

def Start(builder):
    DeleteCmdStart(builder)

def DeleteCmdAddFilter(builder, filter):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(filter), 0)

def AddFilter(builder, filter):
    DeleteCmdAddFilter(builder, filter)

def DeleteCmdAddMany(builder, many):
    builder.PrependBoolSlot(1, many, 0)

def AddMany(builder, many):
    DeleteCmdAddMany(builder, many)

def DeleteCmdEnd(builder):
    return builder.EndObject()

def End(builder):
    return DeleteCmdEnd(builder)
