# automatically generated by the FlatBuffers compiler, do not modify

# namespace: wire

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class DeleteRes(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = DeleteRes()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsDeleteRes(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    @classmethod
    def DeleteResBufferHasIdentifier(cls, buf, offset, size_prefixed=False):
        return flatbuffers.util.BufferHasIdentifier(buf, offset, b"\x4D\x4F\x4F\x52", size_prefixed=size_prefixed)

    # DeleteRes
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # DeleteRes
    def Count(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint64Flags, o + self._tab.Pos)
        return 0

def DeleteResStart(builder):
    builder.StartObject(1)

def Start(builder):
    DeleteResStart(builder)

def DeleteResAddCount(builder, count):
    builder.PrependUint64Slot(0, count, 0)

def AddCount(builder, count):
    DeleteResAddCount(builder, count)

def DeleteResEnd(builder):
    return builder.EndObject()

def End(builder):
    return DeleteResEnd(builder)
