# automatically generated by the FlatBuffers compiler, do not modify

# namespace: wire

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class ExistsRes(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = ExistsRes()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsExistsRes(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    @classmethod
    def ExistsResBufferHasIdentifier(cls, buf, offset, size_prefixed=False):
        return flatbuffers.util.BufferHasIdentifier(buf, offset, b"\x4D\x4F\x4F\x52", size_prefixed=size_prefixed)

    # ExistsRes
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # ExistsRes
    def Exists(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

def ExistsResStart(builder):
    builder.StartObject(1)

def Start(builder):
    ExistsResStart(builder)

def ExistsResAddExists(builder, exists):
    builder.PrependBoolSlot(0, exists, 0)

def AddExists(builder, exists):
    ExistsResAddExists(builder, exists)

def ExistsResEnd(builder):
    return builder.EndObject()

def End(builder):
    return ExistsResEnd(builder)
