# automatically generated by the FlatBuffers compiler, do not modify

# namespace: wire

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class FindCmd(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = FindCmd()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsFindCmd(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    @classmethod
    def FindCmdBufferHasIdentifier(cls, buf, offset, size_prefixed=False):
        return flatbuffers.util.BufferHasIdentifier(buf, offset, b"\x4D\x4F\x4F\x52", size_prefixed=size_prefixed)

    # FindCmd
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # FindCmd
    def Filter(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            from mooracer.wire.Value import Value
            obj = Value()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # FindCmd
    def SortField(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # FindCmd
    def SortDesc(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

    # FindCmd
    def Skip(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint64Flags, o + self._tab.Pos)
        return 0

    # FindCmd
    def Limit(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint64Flags, o + self._tab.Pos)
        return 0

    # FindCmd
    def One(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

def FindCmdStart(builder):
    builder.StartObject(6)

def Start(builder):
    FindCmdStart(builder)

def FindCmdAddFilter(builder, filter):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(filter), 0)

def AddFilter(builder, filter):
    FindCmdAddFilter(builder, filter)

def FindCmdAddSortField(builder, sortField):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(sortField), 0)

def AddSortField(builder, sortField):
    FindCmdAddSortField(builder, sortField)

def FindCmdAddSortDesc(builder, sortDesc):
    builder.PrependBoolSlot(2, sortDesc, 0)

def AddSortDesc(builder, sortDesc):
    FindCmdAddSortDesc(builder, sortDesc)

def FindCmdAddSkip(builder, skip):
    builder.PrependUint64Slot(3, skip, 0)

def AddSkip(builder, skip):
    FindCmdAddSkip(builder, skip)

def FindCmdAddLimit(builder, limit):
    builder.PrependUint64Slot(4, limit, 0)

def AddLimit(builder, limit):
    FindCmdAddLimit(builder, limit)

def FindCmdAddOne(builder, one):
    builder.PrependBoolSlot(5, one, 0)

def AddOne(builder, one):
    FindCmdAddOne(builder, one)

def FindCmdEnd(builder):
    return builder.EndObject()

def End(builder):
    return FindCmdEnd(builder)
