# automatically generated by the FlatBuffers compiler, do not modify

# namespace: wire

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class GroupCmd(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = GroupCmd()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsGroupCmd(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    @classmethod
    def GroupCmdBufferHasIdentifier(cls, buf, offset, size_prefixed=False):
        return flatbuffers.util.BufferHasIdentifier(buf, offset, b"\x4D\x4F\x4F\x52", size_prefixed=size_prefixed)

    # GroupCmd
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # GroupCmd
    def Filter(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            from mooracer.wire.Value import Value
            obj = Value()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # GroupCmd
    def SortField(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # GroupCmd
    def SortDesc(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

    # GroupCmd
    def Skip(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint64Flags, o + self._tab.Pos)
        return 0

    # GroupCmd
    def Limit(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint64Flags, o + self._tab.Pos)
        return 0

    # GroupCmd
    def GroupField(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # GroupCmd
    def AggFn(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 0

    # GroupCmd
    def AggField(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(18))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # GroupCmd
    def GroupSortField(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(20))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # GroupCmd
    def GroupSortDesc(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(22))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

    # GroupCmd
    def GroupLimit(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(24))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint64Flags, o + self._tab.Pos)
        return 0

def GroupCmdStart(builder):
    builder.StartObject(11)

def Start(builder):
    GroupCmdStart(builder)

def GroupCmdAddFilter(builder, filter):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(filter), 0)

def AddFilter(builder, filter):
    GroupCmdAddFilter(builder, filter)

def GroupCmdAddSortField(builder, sortField):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(sortField), 0)

def AddSortField(builder, sortField):
    GroupCmdAddSortField(builder, sortField)

def GroupCmdAddSortDesc(builder, sortDesc):
    builder.PrependBoolSlot(2, sortDesc, 0)

def AddSortDesc(builder, sortDesc):
    GroupCmdAddSortDesc(builder, sortDesc)

def GroupCmdAddSkip(builder, skip):
    builder.PrependUint64Slot(3, skip, 0)

def AddSkip(builder, skip):
    GroupCmdAddSkip(builder, skip)

def GroupCmdAddLimit(builder, limit):
    builder.PrependUint64Slot(4, limit, 0)

def AddLimit(builder, limit):
    GroupCmdAddLimit(builder, limit)

def GroupCmdAddGroupField(builder, groupField):
    builder.PrependUOffsetTRelativeSlot(5, flatbuffers.number_types.UOffsetTFlags.py_type(groupField), 0)

def AddGroupField(builder, groupField):
    GroupCmdAddGroupField(builder, groupField)

def GroupCmdAddAggFn(builder, aggFn):
    builder.PrependUint8Slot(6, aggFn, 0)

def AddAggFn(builder, aggFn):
    GroupCmdAddAggFn(builder, aggFn)

def GroupCmdAddAggField(builder, aggField):
    builder.PrependUOffsetTRelativeSlot(7, flatbuffers.number_types.UOffsetTFlags.py_type(aggField), 0)

def AddAggField(builder, aggField):
    GroupCmdAddAggField(builder, aggField)

def GroupCmdAddGroupSortField(builder, groupSortField):
    builder.PrependUOffsetTRelativeSlot(8, flatbuffers.number_types.UOffsetTFlags.py_type(groupSortField), 0)

def AddGroupSortField(builder, groupSortField):
    GroupCmdAddGroupSortField(builder, groupSortField)

def GroupCmdAddGroupSortDesc(builder, groupSortDesc):
    builder.PrependBoolSlot(9, groupSortDesc, 0)

def AddGroupSortDesc(builder, groupSortDesc):
    GroupCmdAddGroupSortDesc(builder, groupSortDesc)

def GroupCmdAddGroupLimit(builder, groupLimit):
    builder.PrependUint64Slot(10, groupLimit, 0)

def AddGroupLimit(builder, groupLimit):
    GroupCmdAddGroupLimit(builder, groupLimit)

def GroupCmdEnd(builder):
    return builder.EndObject()

def End(builder):
    return GroupCmdEnd(builder)
