# automatically generated by the FlatBuffers compiler, do not modify

# namespace: wire

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class HybridSearchCmd(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = HybridSearchCmd()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsHybridSearchCmd(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    @classmethod
    def HybridSearchCmdBufferHasIdentifier(cls, buf, offset, size_prefixed=False):
        return flatbuffers.util.BufferHasIdentifier(buf, offset, b"\x4D\x4F\x4F\x52", size_prefixed=size_prefixed)

    # HybridSearchCmd
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # HybridSearchCmd
    def TextField(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # HybridSearchCmd
    def VecField(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # HybridSearchCmd
    def QueryText(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # HybridSearchCmd
    def QueryVec(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Float32Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 4))
        return 0

    # HybridSearchCmd
    def QueryVecAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Float32Flags, o)
        return 0

    # HybridSearchCmd
    def QueryVecLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # HybridSearchCmd
    def QueryVecIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        return o == 0

    # HybridSearchCmd
    def Limit(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint64Flags, o + self._tab.Pos)
        return 0

def HybridSearchCmdStart(builder):
    builder.StartObject(5)

def Start(builder):
    HybridSearchCmdStart(builder)

def HybridSearchCmdAddTextField(builder, textField):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(textField), 0)

def AddTextField(builder, textField):
    HybridSearchCmdAddTextField(builder, textField)

def HybridSearchCmdAddVecField(builder, vecField):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(vecField), 0)

def AddVecField(builder, vecField):
    HybridSearchCmdAddVecField(builder, vecField)

def HybridSearchCmdAddQueryText(builder, queryText):
    builder.PrependUOffsetTRelativeSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(queryText), 0)

def AddQueryText(builder, queryText):
    HybridSearchCmdAddQueryText(builder, queryText)

def HybridSearchCmdAddQueryVec(builder, queryVec):
    builder.PrependUOffsetTRelativeSlot(3, flatbuffers.number_types.UOffsetTFlags.py_type(queryVec), 0)

def AddQueryVec(builder, queryVec):
    HybridSearchCmdAddQueryVec(builder, queryVec)

def HybridSearchCmdStartQueryVecVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartQueryVecVector(builder, numElems: int) -> int:
    return HybridSearchCmdStartQueryVecVector(builder, numElems)

def HybridSearchCmdAddLimit(builder, limit):
    builder.PrependUint64Slot(4, limit, 0)

def AddLimit(builder, limit):
    HybridSearchCmdAddLimit(builder, limit)

def HybridSearchCmdEnd(builder):
    return builder.EndObject()

def End(builder):
    return HybridSearchCmdEnd(builder)
