# automatically generated by the FlatBuffers compiler, do not modify

# namespace: wire

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class IndexStat(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = IndexStat()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsIndexStat(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    @classmethod
    def IndexStatBufferHasIdentifier(cls, buf, offset, size_prefixed=False):
        return flatbuffers.util.BufferHasIdentifier(buf, offset, b"\x4D\x4F\x4F\x52", size_prefixed=size_prefixed)

    # IndexStat
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # IndexStat
    def Field(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # IndexStat
    def Entries(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint64Flags, o + self._tab.Pos)
        return 0

    # IndexStat
    def Distinct(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint64Flags, o + self._tab.Pos)
        return 0

    # IndexStat
    def Memory(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint64Flags, o + self._tab.Pos)
        return 0

def IndexStatStart(builder):
    builder.StartObject(4)

def Start(builder):
    IndexStatStart(builder)

def IndexStatAddField(builder, field):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(field), 0)

def AddField(builder, field):
    IndexStatAddField(builder, field)

def IndexStatAddEntries(builder, entries):
    builder.PrependUint64Slot(1, entries, 0)

def AddEntries(builder, entries):
    IndexStatAddEntries(builder, entries)

def IndexStatAddDistinct(builder, distinct):
    builder.PrependUint64Slot(2, distinct, 0)

def AddDistinct(builder, distinct):
    IndexStatAddDistinct(builder, distinct)

def IndexStatAddMemory(builder, memory):
    builder.PrependUint64Slot(3, memory, 0)

def AddMemory(builder, memory):
    IndexStatAddMemory(builder, memory)

def IndexStatEnd(builder):
    return builder.EndObject()

def End(builder):
    return IndexStatEnd(builder)
