# automatically generated by the FlatBuffers compiler, do not modify

# namespace: wire

class IndexKind(object):
    CreateValue = 0
    DropValue = 1
    CreateVector = 2
    DropVector = 3
    CreateText = 4
    DropText = 5
