# automatically generated by the FlatBuffers compiler, do not modify

# namespace: wire

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class IndexCmd(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = IndexCmd()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsIndexCmd(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    @classmethod
    def IndexCmdBufferHasIdentifier(cls, buf, offset, size_prefixed=False):
        return flatbuffers.util.BufferHasIdentifier(buf, offset, b"\x4D\x4F\x4F\x52", size_prefixed=size_prefixed)

    # IndexCmd
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # IndexCmd
    def Kind(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 0

    # IndexCmd
    def Field(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # IndexCmd
    def Dim(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint64Flags, o + self._tab.Pos)
        return 0

def IndexCmdStart(builder):
    builder.StartObject(3)

def Start(builder):
    IndexCmdStart(builder)

def IndexCmdAddKind(builder, kind):
    builder.PrependUint8Slot(0, kind, 0)

def AddKind(builder, kind):
    IndexCmdAddKind(builder, kind)

def IndexCmdAddField(builder, field):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(field), 0)

def AddField(builder, field):
    IndexCmdAddField(builder, field)

def IndexCmdAddDim(builder, dim):
    builder.PrependUint64Slot(2, dim, 0)

def AddDim(builder, dim):
    IndexCmdAddDim(builder, dim)

def IndexCmdEnd(builder):
    return builder.EndObject()

def End(builder):
    return IndexCmdEnd(builder)
