# automatically generated by the FlatBuffers compiler, do not modify

# namespace: wire

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class InsertCmd(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = InsertCmd()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsInsertCmd(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    @classmethod
    def InsertCmdBufferHasIdentifier(cls, buf, offset, size_prefixed=False):
        return flatbuffers.util.BufferHasIdentifier(buf, offset, b"\x4D\x4F\x4F\x52", size_prefixed=size_prefixed)

    # InsertCmd
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # InsertCmd
    def Docs(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            from mooracer.wire.Value import Value
            obj = Value()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # InsertCmd
    def DocsLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # InsertCmd
    def DocsIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        return o == 0

def InsertCmdStart(builder):
    builder.StartObject(1)

def Start(builder):
    InsertCmdStart(builder)

def InsertCmdAddDocs(builder, docs):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(docs), 0)

def AddDocs(builder, docs):
    InsertCmdAddDocs(builder, docs)

def InsertCmdStartDocsVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartDocsVector(builder, numElems: int) -> int:
    return InsertCmdStartDocsVector(builder, numElems)

def InsertCmdEnd(builder):
    return builder.EndObject()

def End(builder):
    return InsertCmdEnd(builder)
