# automatically generated by the FlatBuffers compiler, do not modify

# namespace: wire

class ResponseBody(object):
    NONE = 0
    InsertRes = 1
    FindRes = 2
    CountRes = 3
    ExistsRes = 4
    UpdateRes = 5
    ReplaceRes = 6
    DeleteRes = 7
    SearchRes = 8
    GroupRes = 9
    StatsRes = 10
