# automatically generated by the FlatBuffers compiler, do not modify

# namespace: wire

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class SearchHit(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = SearchHit()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsSearchHit(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    @classmethod
    def SearchHitBufferHasIdentifier(cls, buf, offset, size_prefixed=False):
        return flatbuffers.util.BufferHasIdentifier(buf, offset, b"\x4D\x4F\x4F\x52", size_prefixed=size_prefixed)

    # SearchHit
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # SearchHit
    def Doc(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            from mooracer.wire.Value import Value
            obj = Value()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # SearchHit
    def Score(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float64Flags, o + self._tab.Pos)
        return 0.0

def SearchHitStart(builder):
    builder.StartObject(2)

def Start(builder):
    SearchHitStart(builder)

def SearchHitAddDoc(builder, doc):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(doc), 0)

def AddDoc(builder, doc):
    SearchHitAddDoc(builder, doc)

def SearchHitAddScore(builder, score):
    builder.PrependFloat64Slot(1, score, 0.0)

def AddScore(builder, score):
    SearchHitAddScore(builder, score)

def SearchHitEnd(builder):
    return builder.EndObject()

def End(builder):
    return SearchHitEnd(builder)
