# automatically generated by the FlatBuffers compiler, do not modify

# namespace: wire

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class SearchRes(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = SearchRes()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsSearchRes(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    @classmethod
    def SearchResBufferHasIdentifier(cls, buf, offset, size_prefixed=False):
        return flatbuffers.util.BufferHasIdentifier(buf, offset, b"\x4D\x4F\x4F\x52", size_prefixed=size_prefixed)

    # SearchRes
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # SearchRes
    def Hits(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            from mooracer.wire.SearchHit import SearchHit
            obj = SearchHit()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # SearchRes
    def HitsLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # SearchRes
    def HitsIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        return o == 0

def SearchResStart(builder):
    builder.StartObject(1)

def Start(builder):
    SearchResStart(builder)

def SearchResAddHits(builder, hits):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(hits), 0)

def AddHits(builder, hits):
    SearchResAddHits(builder, hits)

def SearchResStartHitsVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartHitsVector(builder, numElems: int) -> int:
    return SearchResStartHitsVector(builder, numElems)

def SearchResEnd(builder):
    return builder.EndObject()

def End(builder):
    return SearchResEnd(builder)
