# automatically generated by the FlatBuffers compiler, do not modify

# namespace: wire

class Status(object):
    OK = 0
    NotAnObject = 1
    IdMustBeString = 2
    DuplicateId = 3
    IdMismatch = 4
    NoIndex = 5
    PrimaryIndex = 6
    NoMatch = 7
    InvalidUpdate = 8
    VectorDimMismatch = 9
    MalformedRequest = 10
    UnknownCommand = 11
    UnsupportedVersion = 12
    InternalError = 13
