# automatically generated by the FlatBuffers compiler, do not modify

# namespace: wire

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class StatsRes(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = StatsRes()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsStatsRes(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    @classmethod
    def StatsResBufferHasIdentifier(cls, buf, offset, size_prefixed=False):
        return flatbuffers.util.BufferHasIdentifier(buf, offset, b"\x4D\x4F\x4F\x52", size_prefixed=size_prefixed)

    # StatsRes
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # StatsRes
    def Docs(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint64Flags, o + self._tab.Pos)
        return 0

    # StatsRes
    def DocsMemory(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint64Flags, o + self._tab.Pos)
        return 0

    # StatsRes
    def Indexes(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint64Flags, o + self._tab.Pos)
        return 0

    # StatsRes
    def TotalMemory(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint64Flags, o + self._tab.Pos)
        return 0

    # StatsRes
    def PerIndex(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            from mooracer.wire.IndexStat import IndexStat
            obj = IndexStat()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # StatsRes
    def PerIndexLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # StatsRes
    def PerIndexIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        return o == 0

def StatsResStart(builder):
    builder.StartObject(5)

def Start(builder):
    StatsResStart(builder)

def StatsResAddDocs(builder, docs):
    builder.PrependUint64Slot(0, docs, 0)

def AddDocs(builder, docs):
    StatsResAddDocs(builder, docs)

def StatsResAddDocsMemory(builder, docsMemory):
    builder.PrependUint64Slot(1, docsMemory, 0)

def AddDocsMemory(builder, docsMemory):
    StatsResAddDocsMemory(builder, docsMemory)

def StatsResAddIndexes(builder, indexes):
    builder.PrependUint64Slot(2, indexes, 0)

def AddIndexes(builder, indexes):
    StatsResAddIndexes(builder, indexes)

def StatsResAddTotalMemory(builder, totalMemory):
    builder.PrependUint64Slot(3, totalMemory, 0)

def AddTotalMemory(builder, totalMemory):
    StatsResAddTotalMemory(builder, totalMemory)

def StatsResAddPerIndex(builder, perIndex):
    builder.PrependUOffsetTRelativeSlot(4, flatbuffers.number_types.UOffsetTFlags.py_type(perIndex), 0)

def AddPerIndex(builder, perIndex):
    StatsResAddPerIndex(builder, perIndex)

def StatsResStartPerIndexVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartPerIndexVector(builder, numElems: int) -> int:
    return StatsResStartPerIndexVector(builder, numElems)

def StatsResEnd(builder):
    return builder.EndObject()

def End(builder):
    return StatsResEnd(builder)
