# automatically generated by the FlatBuffers compiler, do not modify

# namespace: wire

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class StatsCmd(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = StatsCmd()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsStatsCmd(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    @classmethod
    def StatsCmdBufferHasIdentifier(cls, buf, offset, size_prefixed=False):
        return flatbuffers.util.BufferHasIdentifier(buf, offset, b"\x4D\x4F\x4F\x52", size_prefixed=size_prefixed)

    # StatsCmd
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

def StatsCmdStart(builder):
    builder.StartObject(0)

def Start(builder):
    StatsCmdStart(builder)

def StatsCmdEnd(builder):
    return builder.EndObject()

def End(builder):
    return StatsCmdEnd(builder)
