# automatically generated by the FlatBuffers compiler, do not modify

# namespace: wire

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class TextSearchCmd(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = TextSearchCmd()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsTextSearchCmd(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    @classmethod
    def TextSearchCmdBufferHasIdentifier(cls, buf, offset, size_prefixed=False):
        return flatbuffers.util.BufferHasIdentifier(buf, offset, b"\x4D\x4F\x4F\x52", size_prefixed=size_prefixed)

    # TextSearchCmd
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # TextSearchCmd
    def Field(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # TextSearchCmd
    def Query(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # TextSearchCmd
    def Limit(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint64Flags, o + self._tab.Pos)
        return 0

def TextSearchCmdStart(builder):
    builder.StartObject(3)

def Start(builder):
    TextSearchCmdStart(builder)

def TextSearchCmdAddField(builder, field):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(field), 0)

def AddField(builder, field):
    TextSearchCmdAddField(builder, field)

def TextSearchCmdAddQuery(builder, query):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(query), 0)

def AddQuery(builder, query):
    TextSearchCmdAddQuery(builder, query)

def TextSearchCmdAddLimit(builder, limit):
    builder.PrependUint64Slot(2, limit, 0)

def AddLimit(builder, limit):
    TextSearchCmdAddLimit(builder, limit)

def TextSearchCmdEnd(builder):
    return builder.EndObject()

def End(builder):
    return TextSearchCmdEnd(builder)
