# automatically generated by the FlatBuffers compiler, do not modify

# namespace: wire

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class UpdateCmd(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = UpdateCmd()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsUpdateCmd(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    @classmethod
    def UpdateCmdBufferHasIdentifier(cls, buf, offset, size_prefixed=False):
        return flatbuffers.util.BufferHasIdentifier(buf, offset, b"\x4D\x4F\x4F\x52", size_prefixed=size_prefixed)

    # UpdateCmd
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # UpdateCmd
    def Filter(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            from mooracer.wire.Value import Value
            obj = Value()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # UpdateCmd
    def Update(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            from mooracer.wire.Value import Value
            obj = Value()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # UpdateCmd
    def Many(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

def UpdateCmdStart(builder):
    builder.StartObject(3)

def Start(builder):
    UpdateCmdStart(builder)

def UpdateCmdAddFilter(builder, filter):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(filter), 0)

def AddFilter(builder, filter):
    UpdateCmdAddFilter(builder, filter)

def UpdateCmdAddUpdate(builder, update):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(update), 0)

def AddUpdate(builder, update):
    UpdateCmdAddUpdate(builder, update)

def UpdateCmdAddMany(builder, many):
    builder.PrependBoolSlot(2, many, 0)

def AddMany(builder, many):
    UpdateCmdAddMany(builder, many)

def UpdateCmdEnd(builder):
    return builder.EndObject()

def End(builder):
    return UpdateCmdEnd(builder)
