# automatically generated by the FlatBuffers compiler, do not modify

# namespace: wire

class ValueKind(object):
    Null = 0
    Bool = 1
    I64 = 2
    F64 = 3
    Str = 4
    Array = 5
    Object = 6
