# automatically generated by the FlatBuffers compiler, do not modify

# namespace: wire

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class VectorSearchCmd(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = VectorSearchCmd()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsVectorSearchCmd(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    @classmethod
    def VectorSearchCmdBufferHasIdentifier(cls, buf, offset, size_prefixed=False):
        return flatbuffers.util.BufferHasIdentifier(buf, offset, b"\x4D\x4F\x4F\x52", size_prefixed=size_prefixed)

    # VectorSearchCmd
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # VectorSearchCmd
    def Field(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # VectorSearchCmd
    def Query(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Float32Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 4))
        return 0

    # VectorSearchCmd
    def QueryAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Float32Flags, o)
        return 0

    # VectorSearchCmd
    def QueryLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # VectorSearchCmd
    def QueryIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        return o == 0

    # VectorSearchCmd
    def Limit(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint64Flags, o + self._tab.Pos)
        return 0

def VectorSearchCmdStart(builder):
    builder.StartObject(3)

def Start(builder):
    VectorSearchCmdStart(builder)

def VectorSearchCmdAddField(builder, field):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(field), 0)

def AddField(builder, field):
    VectorSearchCmdAddField(builder, field)

def VectorSearchCmdAddQuery(builder, query):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(query), 0)

def AddQuery(builder, query):
    VectorSearchCmdAddQuery(builder, query)

def VectorSearchCmdStartQueryVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartQueryVector(builder, numElems: int) -> int:
    return VectorSearchCmdStartQueryVector(builder, numElems)

def VectorSearchCmdAddLimit(builder, limit):
    builder.PrependUint64Slot(2, limit, 0)

def AddLimit(builder, limit):
    VectorSearchCmdAddLimit(builder, limit)

def VectorSearchCmdEnd(builder):
    return builder.EndObject()

def End(builder):
    return VectorSearchCmdEnd(builder)
