//! mooracer-wire — MooRacer wire protocol (FlatBuffers).
//!
//! The protocol is defined once in `schema/mooracer.fbs` (workspace root) and
//! code-generated by `flatc --rust`; the generated types are **vendored** into
//! `src/generated.rs` (checked in, like the Python client's `wire/` package), so
//! this crate builds without a system `flatc` at build time — a `flatc` is only
//! needed to *regenerate* the vendored file after editing the schema. This crate
//! includes that module and re-exports it so the server, the Rust client (and
//! any future tooling) share exactly one generated type set. See the
//! "FlatBuffers wire schema (v1)" block in spec.md for the envelope contract.
//!
//! To regenerate: `flatc --rust -o wire/src schema/mooracer.fbs` then rename
//! `wire/src/mooracer_generated.rs` → `wire/src/generated.rs`.
//!
//! Wire framing (length-prefixed frames over TCP) is owned by the server
//! crate; this crate is the pure protocol — encode/decode types only, no I/O.

pub mod generated {
    // flatc-generated: do not edit. Regenerated from schema/mooracer.fbs.
    #![allow(
        dead_code,
        missing_docs,
        non_camel_case_types,
        non_snake_case,
        non_upper_case_globals,
        unused_imports,
        deprecated,
        elided_lifetimes_in_paths,
        mismatched_lifetime_syntaxes,
        unsafe_op_in_unsafe_fn,
        clippy::all
    )]
    include!("generated.rs");
}

pub use generated::mooracer::wire::*;

/// The wire schema version of this build (envelope future-proofing;
/// matches the `version` field default in `Request`/`Response`).
pub const WIRE_VERSION: u64 = 1;

/// The FlatBuffers file identifier written into every frame buffer.
pub const FILE_IDENTIFIER: &str = "MOOR";

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn wire_crate_scaffolds() {
        assert_eq!(FILE_IDENTIFIER, "MOOR");
        assert_eq!(WIRE_VERSION, 1);
        // The generated union discriminants exist and are distinct.
        let cmds = [
            Command::InsertCmd,
            Command::FindCmd,
            Command::CountCmd,
            Command::ExistsCmd,
            Command::UpdateCmd,
            Command::ReplaceCmd,
            Command::DeleteCmd,
            Command::VectorSearchCmd,
            Command::TextSearchCmd,
            Command::HybridSearchCmd,
            Command::GroupCmd,
            Command::StatsCmd,
        ];
        let mut seen = std::collections::HashSet::new();
        for c in cmds {
            assert!(seen.insert(c.0), "duplicate Command discriminant");
        }
        assert_eq!(Command::NONE.0, 0);
    }
}
